import logging
import uuid

from fastapi import APIRouter, Depends, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.database import get_db
from app.core.deps import get_current_user, require_role
from app.core.exceptions import ProblemDetailException
from app.core.pagination import paginate
from app.models.report import Report
from app.models.scan import Scan
from app.models.user import User
from app.schemas.report import (
    ReportDownloadResponse,
    ReportGenerateRequest,
    ReportListItem,
    ReportListResponse,
)
from app.services.reports.service import generate_scan_reports
from app.services.storage.minio_client import presign_get_url

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/reports", tags=["Reports"])


def _verify_report_download_access(report: Report, scan: Scan | None, user: User) -> None:
    """Enforces role and ownership access control for statutory report downloads.

    Rules:
    - Inactive user -> 403 Forbidden
    - Admin -> Global download access allowed
    - Inspector -> Allowed if inspector generated report, performed scan, or has general inspector authority
    - Viewer -> Read-only dashboard user; may only download reports they generated or own
    """
    if not user.is_active:
        raise ProblemDetailException(
            status_code=status.HTTP_403_FORBIDDEN,
            title="Account Inactive",
            detail="Deactivated or pending officer account cannot download statutory records.",
            type_url="https://errors.legalmetro.gov.in/account-inactive",
        )

    if user.role == "admin":
        return

    if user.role == "inspector":
        # Inspector has authority to download reports
        return

    if user.role == "viewer":
        # Check ownership: was it generated by this viewer or did they scan it?
        is_owner = (report.generated_by == user.id) or (scan and scan.scanned_by == user.id)
        if not is_owner:
            raise ProblemDetailException(
                status_code=status.HTTP_403_FORBIDDEN,
                title="Access Forbidden",
                detail="Viewers cannot download statutory enforcement notices without record ownership.",
                type_url="https://errors.legalmetro.gov.in/insufficient-permissions",
            )
        return

    raise ProblemDetailException(
        status_code=status.HTTP_403_FORBIDDEN,
        title="Access Forbidden",
        detail="Unauthorized role cannot download reports.",
        type_url="https://errors.legalmetro.gov.in/insufficient-permissions",
    )


@router.get("", response_model=ReportListResponse, summary="List generated compliance reports")
async def list_reports(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    current_user: User = Depends(require_role("admin", "inspector", "viewer")),
    db: AsyncSession = Depends(get_db),
) -> ReportListResponse:
    query = select(Report).options(
        selectinload(Report.generator),
        selectinload(Report.scan).selectinload(Scan.product),
    )

    reports, total = await paginate(db, query, page, limit, Report.generated_at.desc())

    items: list[ReportListItem] = []
    for r in reports:
        generator = r.generator
        scan = r.scan
        product = scan.product if scan else None
        items.append(
            ReportListItem(
                id=r.id,
                scan_id=r.scan_id,
                pdf_url=r.pdf_url,
                docx_url=r.docx_url,
                generated_by=r.generated_by,
                generator_name=generator.name if generator else None,
                generated_at=r.generated_at,
                product_name=product.name if product else None,
                scan_verdict=scan.verdict if scan else None,
                scan_score=scan.compliance_score if scan else None,
            )
        )

    return ReportListResponse(items=items, total=total, page=page, limit=limit)


@router.post(
    "",
    response_model=ReportListItem,
    status_code=status.HTTP_201_CREATED,
    summary="Generate statutory compliance report (PDF and DOCX)",
)
async def create_report(
    req: ReportGenerateRequest,
    current_user: User = Depends(require_role("admin", "inspector")),
    db: AsyncSession = Depends(get_db),
) -> ReportListItem:
    report = await generate_scan_reports(scan_id=req.scan_id, user=current_user, db=db)

    # Re-query with scan and product for response schema
    stmt = (
        select(Report)
        .options(
            selectinload(Report.generator),
            selectinload(Report.scan).selectinload(Scan.product),
        )
        .where(Report.id == report.id)
    )
    res = await db.execute(stmt)
    full_report = res.scalar_one()

    scan = full_report.scan
    product = scan.product if scan else None

    return ReportListItem(
        id=full_report.id,
        scan_id=full_report.scan_id,
        pdf_url=full_report.pdf_url,
        docx_url=full_report.docx_url,
        generated_by=full_report.generated_by,
        generator_name=full_report.generator.name if full_report.generator else current_user.name,
        generated_at=full_report.generated_at,
        product_name=product.name if product else None,
        scan_verdict=scan.verdict if scan else None,
        scan_score=scan.compliance_score if scan else None,
    )


@router.get(
    "/{id}/download",
    response_model=ReportDownloadResponse,
    summary="Get 5-minute presigned URL for statutory report download (role-checked)",
)
async def download_report(
    id: uuid.UUID,
    format: str = Query(..., description="Report format: pdf or docx"),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> ReportDownloadResponse:
    clean_format = format.strip().lower()
    if clean_format not in ("pdf", "docx"):
        raise ProblemDetailException(
            status_code=status.HTTP_400_BAD_REQUEST,
            title="Unsupported Format",
            detail="Download format must be either 'pdf' or 'docx'.",
            type_url="https://errors.legalmetro.gov.in/invalid-parameter",
        )

    # Query report with scan
    stmt = select(Report).options(selectinload(Report.scan)).where(Report.id == id)
    res = await db.execute(stmt)
    report = res.scalar_one_or_none()

    if not report:
        raise ProblemDetailException(
            status_code=status.HTTP_404_NOT_FOUND,
            title="Report Not Found",
            detail=f"Report '{id}' does not exist.",
            type_url="https://errors.legalmetro.gov.in/report-not-found",
        )

    # Enforce role + ownership access control
    _verify_report_download_access(report=report, scan=report.scan, user=current_user)

    # Determine object key
    object_key = report.pdf_url if clean_format == "pdf" else report.docx_url
    if not object_key:
        raise ProblemDetailException(
            status_code=status.HTTP_404_NOT_FOUND,
            title="Artifact Not Available",
            detail=f"The requested format '{clean_format}' is not available for report '{id}'.",
            type_url="https://errors.legalmetro.gov.in/artifact-not-found",
        )

    # Generate 5-minute presigned GET URL (300 seconds expiry per spec)
    try:
        presigned_url = presign_get_url(object_name=object_key, expires_seconds=300)
    except Exception as exc:
        logger.exception("Failed to generate presigned URL for %s: %s", object_key, exc)
        raise ProblemDetailException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            title="Storage Error",
            detail="Unable to generate secure download link.",
            type_url="https://errors.legalmetro.gov.in/storage-error",
        ) from exc

    filename = f"LegalMetro_Report_{report.scan_id}_{report.id.hex[:6]}.{clean_format}"

    return ReportDownloadResponse(
        report_id=report.id,
        scan_id=report.scan_id,
        format=clean_format,
        download_url=presigned_url,
        expires_in=300,
        filename=filename,
    )
