import React, { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import {
  FileText,
  Download,
  ExternalLink,
  User,
  Loader2,
  AlertCircle,
} from "lucide-react";
import { apiClient } from "@/services/api";

export const ReportsPage: React.FC = () => {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["reports"],
    queryFn: async () => {
      const res = await apiClient.get("/api/v1/reports?limit=50");
      return res.data;
    },
  });

  const reports = data?.items || [];
  const total = data?.total || 0;

  const handleDownload = async (reportId: string, format: "pdf" | "docx") => {
    const key = `${reportId}-${format}`;
    setDownloadingId(key);
    setDownloadError(null);
    try {
      const res = await apiClient.get(`/api/v1/reports/${reportId}/download?format=${format}`);
      const downloadUrl = res.data?.download_url;
      if (downloadUrl) {
        window.open(downloadUrl, "_blank", "noopener,noreferrer");
      }
    } catch (err: any) {
      setDownloadError(
        err.response?.data?.detail || "Failed to download report. Please ensure you have officer privileges."
      );
    } finally {
      setDownloadingId(null);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
        <div>
          <h1 className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600" />
            Statutory Inspection Notices &amp; Reports
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Official inspection summaries and legal metrology violation notices generated for enforcement proceedings.
          </p>
        </div>

        <div className="text-xs font-medium text-slate-500">
          Total Reports Generated: <strong className="text-slate-900">{total}</strong>
        </div>
      </div>

      {downloadError && (
        <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-700 flex items-center gap-2">
          <AlertCircle className="w-4 h-4 flex-shrink-0" />
          <span>{downloadError}</span>
        </div>
      )}

      {/* Reports Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        {isLoading ? (
          <div className="p-12 text-center text-slate-400 text-xs animate-pulse">
            Loading inspection reports archive...
          </div>
        ) : reports.length === 0 ? (
          <div className="p-12 text-center">
            <FileText className="w-10 h-10 text-slate-300 mx-auto mb-2" />
            <div className="text-sm font-semibold text-slate-700">No generated reports available</div>
            <p className="text-xs text-slate-400 mt-1">
              Inspection reports can be generated directly from individual scan detail pages.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-slate-600">
              <thead className="bg-slate-50 text-slate-500 font-semibold border-b border-slate-200 uppercase tracking-wider text-[11px]">
                <tr>
                  <th className="py-3 px-4">Commodity / Scan Reference</th>
                  <th className="py-3 px-4 text-center">Verdict</th>
                  <th className="py-3 px-4 text-center">Score</th>
                  <th className="py-3 px-4">Generated By</th>
                  <th className="py-3 px-4 text-right">Date Generated</th>
                  <th className="py-3 px-4 text-right">Available Downloads</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {reports.map((r: any) => (
                  <tr key={r.id} className="hover:bg-slate-50 transition-colors">
                    <td className="py-3 px-4">
                      <div className="font-semibold text-slate-900">
                        {r.product_name || "Packaged Commodity Label"}
                      </div>
                      <Link
                        to={`/scans/${r.scan_id}`}
                        className="inline-flex items-center gap-1 font-mono text-[11px] text-blue-600 hover:underline mt-0.5"
                      >
                        Scan #{r.scan_id.substring(0, 8)}
                        <ExternalLink className="w-3 h-3" />
                      </Link>
                    </td>
                    <td className="py-3 px-4 text-center">
                      <span
                        className={`inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold ${
                          r.scan_verdict === "compliant"
                            ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                            : r.scan_verdict === "non_compliant"
                            ? "bg-red-50 text-red-700 border border-red-200"
                            : "bg-amber-50 text-amber-700 border border-amber-200"
                        }`}
                      >
                        {r.scan_verdict ? r.scan_verdict.toUpperCase().replace("_", " ") : "EVALUATED"}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-center font-bold text-slate-900">
                      {r.scan_score !== null ? `${r.scan_score}%` : "—"}
                    </td>
                    <td className="py-3 px-4 text-slate-600">
                      <div className="flex items-center gap-1.5">
                        <User className="w-3.5 h-3.5 text-slate-400" />
                        <span>{r.generator_name || "Authorized Officer"}</span>
                      </div>
                    </td>
                    <td className="py-3 px-4 text-right text-slate-400 text-[11px]">
                      {new Date(r.generated_at).toLocaleString("en-IN", {
                        day: "numeric",
                        month: "short",
                        year: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                    <td className="py-3 px-4 text-right whitespace-nowrap">
                      <div className="inline-flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => handleDownload(r.id, "pdf")}
                          disabled={downloadingId === `${r.id}-pdf`}
                          className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold transition-colors disabled:opacity-50"
                        >
                          {downloadingId === `${r.id}-pdf` ? (
                            <Loader2 className="w-3 h-3 animate-spin text-blue-600" />
                          ) : (
                            <Download className="w-3 h-3 text-rose-600" />
                          )}
                          PDF
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDownload(r.id, "docx")}
                          disabled={downloadingId === `${r.id}-docx`}
                          className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold transition-colors disabled:opacity-50"
                        >
                          {downloadingId === `${r.id}-docx` ? (
                            <Loader2 className="w-3 h-3 animate-spin text-blue-600" />
                          ) : (
                            <Download className="w-3 h-3 text-blue-600" />
                          )}
                          DOCX
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};
